"""initial schema

Revision ID: 78e2c6def1e7
Revises: 
Create Date: 2026-09-16 16:34:10.871859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78e2c6def1e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('adresse', sa.String(length=300), nullable=False),
    sa.Column('baujahr', sa.Integer(), nullable=True),
    sa.Column('wohneinheiten', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('kontakt', sa.String(length=200), nullable=True),
    sa.Column('anonymized_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funding_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('building_id', sa.Uuid(), nullable=False),
    sa.Column('jahr', sa.Integer(), nullable=False),
    sa.Column('programm', sa.String(length=50), nullable=False),
    sa.Column('betrag', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ownership',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('building_id', sa.Uuid(), nullable=False),
    sa.Column('von', sa.Date(), nullable=False),
    sa.Column('bis', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('BERATER', 'ADMIN', 'IMMOBILIENBESITZER', 'FACHPARTNER', name='userrole', native_enum=False), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('zeit', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('building_id', sa.Uuid(), nullable=False),
    sa.Column('ownership_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('regelversion', sa.String(length=30), nullable=True),
    sa.Column('regel_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.ForeignKeyConstraint(['ownership_id'], ['ownership.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('typ', sa.Enum('ANGEBOT', 'RECHNUNG', 'FOTO', 'FACHUNTERNEHMERERKLAERUNG', 'BZA', 'TPB', 'BESTAETIGUNG_NACH_DURCHFUEHRUNG', 'ZAHLUNGSNACHWEIS', 'SONSTIGES', name='documenttyp', native_enum=False), nullable=False),
    sa.Column('retention_class', sa.Enum('STEUERLICH', 'FOERDERRECHTLICH', 'FREI_LOESCHBAR', name='retentionclass', native_enum=False), nullable=False),
    sa.Column('dateiname', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    op.drop_table('case')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('ownership')
    op.drop_table('funding_history')
    op.drop_table('person')
    op.drop_table('building')
    # ### end Alembic commands ###
