"""antrags_text tabelle fuer modul 4

Revision ID: 991380b86083
Revises: a0fbe9c8f79f
Create Date: 2026-09-21 19:35:43.421410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '991380b86083'
down_revision: Union[str, Sequence[str], None] = 'a0fbe9c8f79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antrags_text',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('measure_id', sa.Uuid(), nullable=False),
    sa.Column('massnahmenbeschreibung_entwurf', sa.Text(), nullable=False),
    sa.Column('energetischer_mehrwert_entwurf', sa.Text(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(), nullable=False),
    sa.Column('massnahmenbeschreibung_final', sa.Text(), nullable=True),
    sa.Column('energetischer_mehrwert_final', sa.Text(), nullable=True),
    sa.Column('freigegeben', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('measure_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('antrags_text')
    # ### end Alembic commands ###
