"""document speicherpfad, energieausweis dokumenttyp

Revision ID: a0fbe9c8f79f
Revises: 3e2bfa148586
Create Date: 2026-09-21 18:52:51.400126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0fbe9c8f79f'
down_revision: Union[str, Sequence[str], None] = '3e2bfa148586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('speicherpfad', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'speicherpfad')
    # ### end Alembic commands ###
