"""measure-tabelle fuer modul 2

Revision ID: aacc318fd480
Revises: 78e2c6def1e7
Create Date: 2026-09-21 10:31:39.886383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aacc318fd480'
down_revision: Union[str, Sequence[str], None] = '78e2c6def1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measure',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('typ', sa.Enum('DAEMMUNG', 'FENSTER', 'WAERMEPUMPE_LUFT', 'WAERMEPUMPE_ERDWAERME', 'PV_SPEICHER', 'LUEFTUNG', 'BAUBEGLEITUNG', name='measuretyp', native_enum=False), nullable=False),
    sa.Column('jaz', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('machbar', sa.Boolean(), nullable=True),
    sa.Column('hinweis', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measure')
    # ### end Alembic commands ###
